{1: [{'w': ' city winery signature series'}, {'w': ' "joseph arthur: is the'}, {'w': ' blossoming belief" pinot noir'},
     {'w': ' 2017 $55.00'}, {'w': ' city winery au naturel red'}, {'w': ' blend', 'v': ' 2019'}, {'p': ' $32.00'}],
 2: [{'w': ' city winery pet nat "natural'}, {'w': ' sparkling" riesling', 'v': ' 2020'}, {'p': ' $25.00'},
     {'p': ' $17.00'}, {'w': ' city winery signature series'}, {'w': ' "portraits in jazz: thelonious'},
     {'w': ' monk" cabernet sauvignon', 'v': ' 2017'}, {'p': ' $75.00'}, {'w': ' city winery rose is', 'v': ' a rose'},
     {'w': ' rose is a rose', 'v': ' 2019'}],
 3: [{'w': ' city winery classic white and'}, {'w': ' city winery classic white and'}, {'w': ' rose wine 6-pack'},
     {'w': ' rose wine 3-pack'}, {'p': ' $140.00'}, {'w': ' city winery classic, white, red,'},
     {'w': ' and rose wine 12-pack'}, {'w': ' city winery chazak port'}, {'p': ' $240.00'}, {'p': ' $70.00'}],
 4: [{'p': ' $25.00'}, {'p': ' $45.00'}, {'w': ' city winery sohovignon'}, {'w': ' sauvignon blanc', 'v': ' 2020'},
     {'p': ' $18.00'}, {'w': ' city winery reserve pinot noir'}, {'w': ' cuvee bacigalupi', 'v': ' 2019'},
     {'w': ' city winery spring street pinot'}, {'w': ' noir 6-pack'}, {'p': ' $153.00'}], 5: []}
